spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    name: property_db

  jpa:
    hibernate:
      ddl-auto: update   # consider 'validate' or 'none' in strict prod
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    database: mysql

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

aws:
  s3:
    bucket_name: ${S3_BUCKET_NAME}
    region: ${AWS_REGION:ap-south-1} # fallback to ap-south-1 if not set

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 900 # 15 minutes
    token-prefix: "Bearer "
    header-string: "Authorization"
    enable-token-blacklist: false
    refresh-token-expiration-seconds: 259200 # 3 days
