spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/property_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  docker:
    compose:
      file: docker-compose.yml
      enabled: false

aws:
  s3:
    region: ap-south-1
    bucket_name: parser-engine-bucket
    access_key: test
    secret_key: test