spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${{ env.MYSQL_URL }}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    name: property_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  docker:
    compose:
      file: docker-compose.yml
      enabled: true

aws:
  s3:
    arn: ${{ env.AWS_S3_ARN }}
    bucket_name: ${{ env.S3_BUCKET_NAME }}
    access_key: ${{ env.ACCESS_KEY }}
    secret_key: ${{ env.SECRET_KEY }}